name: KDE Plasma Desktop + Chrome + VNC + ngrok

on:
  workflow_dispatch:
    inputs:
      resolution:
        description: Display resolution (e.g., 1920x1080)
        required: false
        default: 1920x1080
      keep_alive:
        description: Minutes to keep alive (max 360)
        required: false
        default: 60

jobs:
  kde-plasma-chrome:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    env:
      USERNAME: runner
      PASSWORD: ${{ secrets.VNC_PASSWORD || 'kde12345' }}
      RESOLUTION: ${{ github.event.inputs.resolution || '1920x1080' }}
      KEEP_MINUTES: ${{ github.event.inputs.keep_alive || '60' }}
      NGROK_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    steps:
      - name: Validate secrets
        run: |
          if [ -z "${NGROK_TOKEN}" ]; then
            echo "❌ Set NGROK_AUTH_TOKEN secret in repo settings"
            exit 1
          fi

      - name: Install KDE Plasma + VNC
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y \
            kde-plasma-desktop \
            tigervnc-standalone-server \
            tigervnc-common \
            wget unzip curl jq

      - name: Install Google Chrome
        run: |
          wget -q -O chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./chrome.deb
          rm chrome.deb

      - name: Setup VNC config
        run: |
          mkdir -p "$HOME/.vnc"
          echo "${PASSWORD}" | vncpasswd -f > "$HOME/.vnc/passwd"
          chmod 600 "$HOME/.vnc/passwd"
          
          # Create xstartup for KDE Plasma with autostart
          cat > "$HOME/.vnc/xstartup" << 'EOF'
#!/bin/bash
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# Start KDE Plasma
exec startplasma-x11
EOF
          chmod +x "$HOME/.vnc/xstartup"

          # Create autostart script to launch Chrome
          mkdir -p "$HOME/.config/autostart"
          cat > "$HOME/.config/autostart/chrome.desktop" << 'EOF'
[Desktop Entry]
Type=Application
Name=Chrome
Exec=google-chrome --no-sandbox --disable-dev-shm-usage
Icon=google-chrome
EOF

      - name: Start VNC server
        run: |
          vncserver -kill :1 || true
          vncserver :1 -geometry "${RESOLUTION}" -depth 24
          echo "✅ VNC started on :1"

      - name: Setup ngrok
        run: |
          wget -q -O ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip -qq ngrok.zip
          sudo install ngrok /usr/local/bin/
          ngrok config add-authtoken "${NGROK_TOKEN}"

      - name: Start ngrok tunnel
        run: |
          ngrok tcp 5901 --region=in --log=stdout > ngrok.log 2>&1 &
          sleep 8
          URL=$(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          if [ -z "$URL" ] || [ "$URL" = "null" ]; then
            echo "❌ Failed to get ngrok URL"
            cat ngrok.log
            exit 1
          fi
          echo "🔗 CONNECT HERE: ${URL}"
          echo "👤 USER: ${USERNAME}"
          echo "🔑 PASS: ${PASSWORD}"
          echo "🌍 CHROME WILL AUTO-START - BROWSE AFTER CONNECTING!"

      - name: Keep alive
        run: |
          echo "⏰ Keeping session alive for ${KEEP_MINUTES} minutes..."
          sleep $(( KEEP_MINUTES * 60 ))
