name: Setup XFCE Desktop + ngrok VNC Tunnel (India)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-desktop-environment:
    runs-on: ubuntu-22.04
    env:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      USERNAME: runner
      PASSWORD: ${{ secrets.VNC_PASSWORD || 'runner' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure User Permissions
        run: |
          echo "${USERNAME}:${PASSWORD}" | sudo chpasswd
          echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${USERNAME}
          sudo usermod -aG video ${USERNAME}

      - name: Update System Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get upgrade -y -qq

      - name: Install Desktop Environment
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
            xfce4 \
            xfce4-goodies \
            xorg \
            dbus-x11 \
            tigervnc-standalone-server \
            tigervnc-common \
            firefox \
            xfce4-terminal \
            thunar-archive-plugin \
            arc-theme \
            papirus-icon-theme

      - name: Configure VNC Server
        run: |
          sudo mkdir -p /home/${USERNAME}/.vnc
          sudo chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.vnc
          
          sudo -u ${USERNAME} bash -c "
            echo '${PASSWORD}' | vncpasswd -f > /home/${USERNAME}/.vnc/passwd
            chmod 600 /home/${USERNAME}/.vnc/passwd
            
            cat << 'EOT' > /home/${USERNAME}/.vnc/xstartup
#!/bin/bash
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export XKL_XMODMAP_DISABLE=1
export XDG_CURRENT_DESKTOP=XFCE
export XDG_SESSION_TYPE=x11
export XDG_SESSION_DESKTOP=xfce
export DESKTOP_SESSION=xfce
exec startxfce4
EOT
            chmod +x /home/${USERNAME}/.vnc/xstartup
          "

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update -qq
          sudo apt-get install -y -qq ngrok
          ngrok --version

      - name: Start VNC Server
        run: |
          sudo -u ${USERNAME} vncserver :1 -geometry 1920x1080 -depth 24 -localhost no
          echo "VNC server started on display :1"

      - name: Configure ngrok Tunnel
        run: |
          sudo -u ${USERNAME} ngrok authtoken ${NGROK_AUTH_TOKEN}
          sudo -u ${USERNAME} nohup ngrok tcp 5901 --region=in > /tmp/ngrok.log 2>&1 &
          echo "Waiting for ngrok tunnel..."
          sleep 8

      - name: Display Connection Information
        run: |
          NGROK_URL=$(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url' 2>/dev/null || echo "")
          if [ -z "$NGROK_URL" ] || [ "$NGROK_URL" = "null" ]; then
            echo "❌ Failed to establish ngrok tunnel"
            echo "Log output:"
            cat /tmp/ngrok.log || echo "No log found"
            exit 1
          fi
          
          echo "✅ SUCCESS: Desktop environment is ready!"
          echo ""
          echo "🔗 CONNECT TO DESKTOP:"
          echo "   VNC Address: ${NGROK_URL#tcp://}"
          echo "   Username: ${USERNAME}"
          echo "   Password: ${PASSWORD}"
          echo ""
          echo "💡 TIPS:"
          echo "   • Use any VNC client to connect"
          echo "   • Session will remain active for 6 hours"
          echo "   • Firefox and terminal are pre-installed"

      - name: Keep Workflow Alive
        run: |
          echo "🖥️ Desktop session active - waiting for connections..."
          timeout 360m bash -c "while true; do sleep 60; done" || echo "Session expired after 6 hours"
