name: Setup XFCE Runner + ngrok v3 (India) with VNC
on: 
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-gui-runner:
    runs-on: ubuntu-latest
    env:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      USERNAME: runner
      PASSWORD: runner

    steps:
      - uses: actions/checkout@v4

      - name: Ensure runner user has sudo
        run: |
          echo "${USERNAME}:${PASSWORD}" | sudo chpasswd
          echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${USERNAME}

      - name: Install XFCE + VNC server
        run: |
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq xfce4 xfce4-goodies xorg dbus-x11 tigervnc-standalone-server tigervnc-common
          # Create VNC config for the user
          mkdir -p /home/${USERNAME}/.vnc
          echo "${PASSWORD}" | vncpasswd -f > /home/${USERNAME}/.vnc/passwd
          chmod 600 /home/${USERNAME}/.vnc/passwd
          echo "#!/bin/bash
          xrdb $HOME/.Xresources
          startxfce4 &" | sudo tee /home/${USERNAME}/.vnc/xstartup
          chmod +x /home/${USERNAME}/.vnc/xstartup
          sudo chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.vnc

      - name: Install ngrok v3
        run: |
          sudo apt-get install -y -qq wget unzip
          wget -q -O ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip -qq ngrok.zip
          sudo mv ngrok /usr/local/bin/
          ngrok version

      - name: Start VNC server
        run: |
          sudo -u ${USERNAME} vncserver :1 -geometry 1920x1080 -depth 24
          echo "VNC server started on display :1"

      - name: Start ngrok TCP Tunnel for VNC (India)
        run: |
          nohup ngrok tcp 5901 --authtoken ${NGROK_AUTH_TOKEN} --region=in --log=stdout > ngrok.log 2>&1 &
          echo "Waiting for ngrok to generate public URL..."
          sleep 10
          NGROK_URL=$(grep -o 'tcp://[0-9a-z.:]*' ngrok.log | head -n 1)
          if [ -z "$NGROK_URL" ]; then
              echo "Error: ngrok tunnel did not start!"
              cat ngrok.log
              exit 1
          fi
          echo "=== FINAL CONNECTION INFO ==="
          echo "USERNAME: ${USERNAME}"
          echo "VNC Password: ${PASSWORD}"
          echo "Connect via VNC using: ${NGROK_URL}"

          # Keep the runner alive
          while true; do
            sleep 600
     
done
